module.exports = {
  apps: [
    {
      name: "rathburn-online",
      script: "./.next/standalone/server.js",
      cwd: "/home/ec2-user/rathburn-online",
      args: "-p 3000",
      watch: false,
      instances: "1",
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: 3000,
        NEXT_PUBLIC_API_URL: "http://localhost:3000/api/",
        __NEXT_PRIVATE_STANDALONE_CONFIG: "true",
        NEXT_TELEMETRY_DISABLED: 1,
      },
      env_file: ".next/standalone/.env",
    },
  ],
};

// The pm2 command generated by this configuration is:
// pm2 start .next/standalone/server.js --name "rathburn-online" -- -p 3000 --cwd /home/ec2-user/rathburn-online --env production --env-file .next/standalone/.env --instances 1 --exec-mode fork --watch false
