module.exports = {
  apps: [
    {
      name: "rathburn-online",
      script: ".next/standalone/server.js",
      args: "-p 3000",
      cwd: "/home/ec2-user/rathburn-online",
      watch: false,
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: "3000",
        // Set the production API URL to the EC2 instance's public DNS or IP
        // IMPORTANT: Update this with your actual EC2 public DNS or IP
        NEXT_PUBLIC_API_URL: "http://18.175.182.134:3000/api/",
      },
      // This ensures environment variables from .env are loaded
      env_file: ".next/standalone/.env",
    },
  ],
};

// The pm2 command generated by this configuration is:
// pm2 start .next/standalone/server.js --name "rathburn-online" -- -p 3000 --cwd /home/ec2-user/rathburn-online --env production --env-file .next/standalone/.env --instances 1 --exec-mode fork --watch false
