name: Deploy to EC2

on:
  push:
    branches: [main]
  workflow_dispatch: # Allows the workflow to be manually triggered from the GitHub Actions tab

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js (adjust the version as needed)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.20"

      # Build without database operations
      - name: Install and Build
        run: |
          # Install dependencies
          npm install --omit=dev --omit=optional

          # Generate Prisma client (this doesn't require DB connection)
          cd database && npx prisma generate && cd ..

          # Build the application
          npm run build

          # Copy assets to standalone directory
          mkdir -p .next/standalone/.next/static
          cp -r .next/static/* .next/standalone/.next/static/
          [ -d "public" ] && cp -r public .next/standalone/ || echo "No public folder"

      # Deploy to EC2 - server will handle DB operations
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ec2-user/rathburn-online
            pm2 stop rathburn-online || true
            pm2 delete rathburn-online || true
            git pull origin main
            npm install --omit=dev --omit=optional

            # Run database operations on server where DB is accessible
            cd database && npx prisma db pull && npx prisma generate && cd ..

            npm run build
            cp .env .next/standalone/
            mkdir -p .next/standalone/.next/static
            cp -r .next/static/* .next/standalone/.next/static/
            [ -d "public" ] && cp -r public .next/standalone/ || echo "No public folder"
            pm2 start ecosystem.config.js
            pm2 save
